# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
spring:
  application:
    name: oj-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://42.194.144.223:3306/my_oj
#    username: my_oj_user
#    password: 12345678
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_oj
    username: root
    password: chen0828!csq
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: 42.194.144.223
    port: 6379
    timeout: 5000
    password: abc123456
  mail:
    # 邮件配置信息
    # 163邮箱的SMTP服务器配置
    protocol: smtp  # 使用的邮件协议
    default-encoding: UTF-8  # 默认编码格式
    test-connection: true # 启动时是否测试连接
    host: smtp.163.com  # SMTP服务器地址
    port: 465 # 端口号（默认为SMTP的标准端口）
    username: cmh22408@163.com # 发件人邮箱地址
    password: QDTXLMQLCARYHZYS  # 发件人邮箱密码
    properties:
      # 邮件客户端属性配置
      mail.smtp.auth: true  # 启用SMTP身份验证
      mail.smtp.starttls.enable: true  # 启用STARTTLS协议
      mail.smtp.starttls.required: true  # 要求使用STARTTLS协议
      mail.smtp.socketFactory.port: 465  # SSL连接使用的端口号
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory  # SSL连接的SocketFactory类
      mail.smtp.socketFactory.fallback: false  # SSL连接失败时不回退到非加密连接
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
    elasticsearch:
      uris: http://localhost:9200
      username: root
      password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置


# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.oj.controller
# 代码沙箱配置
codesandbox:
  type: remote
